import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/positive-adversity-logo.webp";

const DCF_SUPERVISION_FEE = 11.25;

function formatCurrency(value) {
  return `$${Number(value || 0).toFixed(2)}`;
}

function formatDate(value) {
  if (!value) return "-";

  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return String(value);

  return d.toLocaleDateString();
}

function getImageFormatFromDataUrl(dataUrl) {
  if (dataUrl.startsWith("data:image/png")) return "PNG";
  if (dataUrl.startsWith("data:image/jpeg")) return "JPEG";
  if (dataUrl.startsWith("data:image/jpg")) return "JPEG";
  if (dataUrl.startsWith("data:image/webp")) return "WEBP";
  return "PNG";
}

async function imageToDataUrl(imageSrc) {
  const response = await fetch(imageSrc);
  const blob = await response.blob();

  return await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

function getSupervisionFee(entry) {
  const serviceType = String(entry?.serviceType || "").trim().toLowerCase();
  return Number(entry?.supervisionFee || 0) || (serviceType === "dcf" ? DCF_SUPERVISION_FEE : 0);
}

function getInternalTotal(entry) {
  const hours = Number(entry?.hours || 0);
  const internalRate = Number(entry?.internalRate || 0);
  const supervisionFee = getSupervisionFee(entry);

  if (entry?.internalTotal != null) {
    return Number(entry.internalTotal || 0);
  }

  return Number((hours * internalRate + supervisionFee).toFixed(2));
}

export async function exportEntriesPdf({
  entries = [],
  selectedMonth = "all",
  visibleUserLabel = "All Users",
}) {
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();

  let logoDataUrl = null;

  try {
    logoDataUrl = await imageToDataUrl(logo);
  } catch (error) {
    console.error("Failed to load logo for PDF:", error);
  }

  if (logoDataUrl) {
    const imageFormat = getImageFormatFromDataUrl(logoDataUrl);
    doc.addImage(logoDataUrl, imageFormat, 10, 8, 22, 22);
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Positive Adversity Report", pageWidth - 10, 15, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`User Filter: ${visibleUserLabel}`, pageWidth - 10, 22, { align: "right" });
  doc.text(
    `Month Filter: ${selectedMonth === "all" ? "All Months" : selectedMonth}`,
    pageWidth - 10,
    28,
    { align: "right" },
  );
  doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - 10, 34, {
    align: "right",
  });

  const totals = entries.reduce(
    (acc, entry) => {
      const hours = Number(entry?.hours || 0);
      const supervisionFee = getSupervisionFee(entry);
      const internalTotal = getInternalTotal(entry);

      acc.entries += 1;
      acc.hours += hours;
      acc.supervisionFee += supervisionFee;
      acc.internalTotal += internalTotal;

      return acc;
    },
    {
      entries: 0,
      hours: 0,
      supervisionFee: 0,
      internalTotal: 0,
    },
  );

  doc.setDrawColor(220, 220, 220);
  doc.line(10, 40, pageWidth - 10, 40);

  autoTable(doc, {
    startY: 46,
    head: [[
      "Student",
      "User",
      "Service",
      "Date",
      "Hours",
      "DCF Fee",
      "Internal Total",
    ]],
    body: entries.map((entry) => [
      entry?.student || "-",
      entry?.userName || entry?.userEmail || entry?.userId || "-",
      entry?.serviceType || "-",
      entry?.date || formatDate(entry?.startTime),
      Number(entry?.hours || 0).toFixed(2),
      formatCurrency(getSupervisionFee(entry)),
      formatCurrency(getInternalTotal(entry)),
    ]),
    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: 2.5,
      overflow: "linebreak",
      valign: "middle",
    },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    theme: "grid",
    margin: { left: 10, right: 10 },
    didDrawPage: () => {
      doc.setFontSize(9);
      doc.setTextColor(110);
      doc.text("Generated by Positive Adversity", 10, 200);
    },
  });

  const finalY = doc.lastAutoTable?.finalY || 60;
  const summaryY = finalY + 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);

  doc.text(`Entries: ${totals.entries}`, 10, summaryY);
  doc.text(`Hours: ${totals.hours.toFixed(2)}`, 70, summaryY);
  doc.text(`DCF Fee Total: ${formatCurrency(totals.supervisionFee)}`, 150, summaryY);
  doc.text(`Internal Total: ${formatCurrency(totals.internalTotal)}`, 255, summaryY, {
    align: "right",
  });

  const safeUser = String(visibleUserLabel || "all_users")
    .replace(/[^a-z0-9]/gi, "_")
    .toLowerCase();

  const safeMonth = String(selectedMonth || "all_months")
    .replace(/[^a-z0-9]/gi, "_")
    .toLowerCase();

  doc.save(`positive_adversity_report_${safeUser}_${safeMonth}.pdf`);
}